### ISSUE TITLE
Issue with projectile dependency

### ISSUE THREAD

**Issue by Ergus** [nbfalcon/ptemplate-templates#1]
Hi:

I have tried to use the messon template just to test the package, but I get an error that projectile is required. 

I don't have projectile because the new emacs api `project.el` solves my needs. And maybe yours too. Else, then projectile should be added as a package dependency, so it gets automatically installed after pcomplete-templates.

Best,
Ergus

**Comment by Ergus** [comment]
Sorry now I see it requires to read the readme... this is indeed unfortunate but ok

**Comment by nbfalcon** [comment]
I'll look into removing the projectile dependency.

**Comment by nbfalcon** [comment]
`projectile` is no longer needed to use `ptemplate-templates`.
